language: minimal

services:
  - docker

jobs:
  include:
    - env: DRUPAL_VERSION=8.8
    - env: DRUPAL_VERSION=9

before_script:
  - docker-compose run -rm drupal composer require drupal/core-recommended $DRUPAL_VERSION
  - docker-compose run -rm drupal composer install
  - docker-compose run -rm drupal composer si
  - docker-compose up -d

script:
  # This is also run by grumphp, but running it individually gives more output on travis
  - docker-compose run -rm drupal composer phpcs
  - docker-compose run -rm drupal composer lint
  - docker-compose run -rm drupal composer unit
  - docker-compose run -rm drupal composer phpstan

notifications:
  email: false
